/*
 * DVD Store Multi-Database Orchestrator
 * Launches multiple database drivers simultaneously for side-by-side comparison
 *
 *  Generated by claude-code.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
 */

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace DvdStoreOrchestrator
{
  class TargetConfig
  {
    public string DbType { get; set; } = "";
    public string Executable { get; set; } = "";
    public string Hostname { get; set; } = "";
    public string Label { get; set; } = "";
  }

  class BenchmarkResults
  {
    public string DbType { get; set; } = "";
    public int Opm { get; set; }
    public int TotalOrders { get; set; }
    public double AvgRt { get; set; }
  }

  class Program
  {
    static async Task Main(string[] args)
    {
      if (args.Length == 0)
      {
        ShowUsage();
        return;
      }

      string configFile = args[0];

      if (!File.Exists(configFile))
      {
        Console.WriteLine($"Error: Config file '{configFile}' not found");
        return;
      }

      Console.WriteLine("========== DVD Store Multi-Database Orchestrator ==========");
      Console.WriteLine($"Config: {configFile}");
      Console.WriteLine($"Start:  {DateTime.Now:yyyy-MM-dd HH:mm:ss}\n");

      // Parse configuration
      var (commonParams, targets) = ParseConfig(configFile);

      if (targets.Count == 0)
      {
        Console.WriteLine("Error: No targets defined in config file");
        return;
      }

      Console.WriteLine($"Found {targets.Count} database targets:");
      foreach (var target in targets)
      {
        Console.WriteLine($"  [{target.DbType}:{target.Hostname}]");
      }
      Console.WriteLine();

      // Pre-flight check: verify executables exist
      Console.WriteLine("Checking executables...");
      bool allExist = true;
      foreach (var target in targets)
      {
        bool exists = File.Exists(target.Executable);
        string status = exists ? "OK" : "NOT FOUND";
        Console.WriteLine($"  [{target.DbType}:{target.Hostname}] {target.Executable,-40} {status}");
        if (!exists)
          allExist = false;
      }
      Console.WriteLine();

      if (!allExist)
      {
        Console.WriteLine("ERROR: Missing executables detected.");
        Console.WriteLine("Run 'dotnet publish -c Release -o .' in each database directory first.");
        return;
      }

      // Launch all drivers in parallel
      var tasks = new List<Task<(TargetConfig, int)>>();

      foreach (var target in targets)
      {
        tasks.Add(Task.Run(() => LaunchDriver(target, commonParams)));
      }

      // Wait for all to complete
      Console.WriteLine("Launching drivers...\n");
      var results = await Task.WhenAll(tasks);

      // Simple summary
      Console.WriteLine("\n========== ORCHESTRATOR SUMMARY ==========");
      Console.WriteLine($"Completed: {DateTime.Now:yyyy-MM-dd HH:mm:ss}\n");

      foreach (var (target, exitCode) in results)
      {
        string status = exitCode == 0 ? "SUCCESS" : $"FAILED (exit {exitCode})";
        Console.WriteLine($"  [{target.DbType}:{target.Hostname}] {status}");
      }

      Console.WriteLine("\nCheck individual driver output logs for detailed results:");
      foreach (var target in targets)
      {
        Console.WriteLine($"  {target.DbType}_{target.Hostname}_output.log");
      }

      // Parse and display comparison table
      var parsedResults = ResultsParser.ParseAllResults(targets);
      ResultsParser.PrintComparisonTable(parsedResults);
    }

    static (Dictionary<string, string>, List<TargetConfig>) ParseConfig(string configFile)
    {
      var commonParams = new Dictionary<string, string>();
      var targets = new List<TargetConfig>();

      foreach (var line in File.ReadAllLines(configFile))
      {
        string trimmed = line.Trim();

        // Skip comments and empty lines
        if (trimmed.StartsWith("#") || string.IsNullOrWhiteSpace(trimmed))
          continue;

        if (!trimmed.Contains('='))
          continue;

        string[] parts = trimmed.Split('=', 2);
        string key = parts[0].Trim();
        string value = parts[1].Trim();

        if (key.StartsWith("target_"))
        {
          // Format: mysql/ds36mysqldriverlinux:10.31.46.50
          string[] targetParts = value.Split(':');
          if (targetParts.Length >= 2)
          {
            string executable = targetParts[0];
            string hostname = targetParts[1];

            // Extract database type from path (directory name before executable)
            string dbType = "unknown";
            if (executable.Contains('/'))
            {
              string[] pathParts = executable.Split('/');
              // Get the directory name (e.g., "mysql" from "mysql/ds36mysqldriverlinux")
              dbType = pathParts[pathParts.Length - 2];
            }

            targets.Add(new TargetConfig
            {
              DbType = dbType,
              Executable = executable,
              Hostname = hostname,
              Label = $"{dbType}@{hostname}"
            });
          }
        }
        else
        {
          commonParams[key] = value;
        }
      }

      // Detect duplicate targets (same hostname:dbtype combination)
      var duplicates = targets
        .GroupBy(t => $"{t.DbType}:{t.Hostname}")
        .Where(g => g.Count() > 1)
        .Select(g => g.Key)
        .ToList();

      if (duplicates.Any())
      {
        Console.WriteLine("Error: Duplicate targets detected in config file:");
        foreach (var dup in duplicates)
        {
          Console.WriteLine($"  {dup} appears multiple times");
        }
        Environment.Exit(1);
      }

      return (commonParams, targets);
    }

    static (TargetConfig, int) LaunchDriver(TargetConfig target, Dictionary<string, string> commonParams)
    {
      // Create temporary config file for this target (cross-platform temp directory)
      string tempConfig = Path.Combine(Path.GetTempPath(), $"{target.DbType}_config_{DateTime.Now:yyyyMMddHHmmss}.txt");

      using (var writer = new StreamWriter(tempConfig))
      {
        // Write target-specific parameter
        writer.WriteLine($"target={target.Hostname}");

        // Write all common parameters
        foreach (var kvp in commonParams)
        {
          writer.WriteLine($"{kvp.Key}={kvp.Value}");
        }
      }

      Console.WriteLine($"[{target.DbType}:{target.Hostname}] Launching with config: {tempConfig}");

      // Launch driver process
      // Use absolute paths for both executable and working directory
      string fullExecutablePath = Path.GetFullPath(target.Executable);
      string workingDir = Path.GetDirectoryName(fullExecutablePath) ?? ".";

      var process = new Process
      {
        StartInfo = new ProcessStartInfo
        {
          FileName = fullExecutablePath,
          Arguments = $"--config_file={Path.GetFullPath(tempConfig)}",
          WorkingDirectory = workingDir,
          RedirectStandardOutput = true,
          RedirectStandardError = true,
          UseShellExecute = false,
          CreateNoWindow = true
        }
      };

      string outputLog = $"{target.DbType}_{target.Hostname}_output.log";

      using (var logWriter = new StreamWriter(outputLog))
      {
        // Create label: dbtype (left-aligned, 9 chars) + ": " + hostname (right-aligned, 11 chars)
        string shortHostname = target.Hostname.Length > 11 ? target.Hostname.Substring(0, 11) : target.Hostname;
        string label = $"{target.DbType,-9}: {shortHostname,11}";

        process.OutputDataReceived += (sender, e) =>
        {
          if (e.Data != null)
          {
            Console.WriteLine($"[{label}] {e.Data}");
            logWriter.WriteLine(e.Data);
          }
        };

        process.ErrorDataReceived += (sender, e) =>
        {
          if (e.Data != null)
          {
            Console.WriteLine($"[{label}] ERROR: {e.Data}");
            logWriter.WriteLine($"ERROR: {e.Data}");
          }
        };

        process.Start();
        process.BeginOutputReadLine();
        process.BeginErrorReadLine();
        process.WaitForExit();

        int exitCode = process.ExitCode;
        Console.WriteLine($"[{target.DbType}:{target.Hostname}] Completed with exit code {exitCode}");

        return (target, exitCode);
      }
    }

    static void ShowUsage()
    {
      Console.WriteLine("DVD Store Multi-Database Orchestrator");
      Console.WriteLine("Usage: dotnet run <config_file>");
      Console.WriteLine();
      Console.WriteLine("Config file format:");
      Console.WriteLine("  # Common benchmark parameters");
      Console.WriteLine("  run_time=10");
      Console.WriteLine("  n_threads=16");
      Console.WriteLine("  analytics_interval=2");
      Console.WriteLine();
      Console.WriteLine("  # Database targets (executable:hostname)");
      Console.WriteLine("  # Build binaries first: cd mysql && dotnet publish -c Release -o .");
      Console.WriteLine("  target_1=mysql/mysql_ds:10.31.46.50");
      Console.WriteLine("  target_2=sqlserver/sqlserver_ds:10.31.46.51");
      Console.WriteLine("  target_3=pgsql/pgsql_ds:10.31.46.52");
    }
  }
}
