/*
 * DVD Store 3.6 - ResultsParser.cs
 *
 *  Generated by claude-code.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA  
 *  */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;

namespace DvdStoreOrchestrator
{
  class DatabaseResults
  {
    public string DbType { get; set; } = "";
    public string Hostname { get; set; } = "";
    public int Opm { get; set; }
    public double AvgRt { get; set; }
    public int TotalOrders { get; set; }
    public double RollbackPct { get; set; }
    public double ElapsedTime { get; set; }

    // Analytics response times
    public double MembershipAnalyticsRt { get; set; }
    public double NewCustomerAnalyticsRt { get; set; }
    public double ReviewAnalyticsRt { get; set; }
    public double PricePointAnalyticsRt { get; set; }
    public double InventoryAnalyticsRt { get; set; }

    // Manager operation response times
    public double AddProductRt { get; set; }
    public double RemoveReviewByProductRt { get; set; }
    public double RemoveUnhelpfulReviewsRt { get; set; }
    public double RemoveReviewsByDateRt { get; set; }
    public double AdjustPricesRt { get; set; }
    public double BulkPriceAdjustmentRt { get; set; }
    public double MarkSpecialsRt { get; set; }
    public double ExpireMembershipsRt { get; set; }
    public double PurgeOldOrdersRt { get; set; }
    public double UpgradeMembershipRt { get; set; }
    public double PromotionalMembershipRt { get; set; }
  }

  class ResultsParser
  {
    public static List<DatabaseResults> ParseAllResults(List<TargetConfig> targets)
    {
      var results = new List<DatabaseResults>();

      foreach (var target in targets)
      {
        string logFile = $"{target.DbType}_{target.Hostname}_output.log";

        if (!File.Exists(logFile))
        {
          Console.WriteLine($"Warning: Log file not found: {logFile}");
          continue;
        }

        var result = ParseLogFile(logFile, target);
        if (result != null)
        {
          results.Add(result);
        }
      }

      return results;
    }

    private static DatabaseResults? ParseLogFile(string logFile, TargetConfig target)
    {
      var result = new DatabaseResults
      {
        DbType = target.DbType,
        Hostname = target.Hostname
      };

      try
      {
        string[] lines = File.ReadAllLines(logFile);

        foreach (string line in lines)
        {
          // Parse: "Orders Per Minute:      25478 OPM"
          var opmMatch = Regex.Match(line, @"Orders Per Minute:\s+(\d+)\s+OPM");
          if (opmMatch.Success)
          {
            result.Opm = int.Parse(opmMatch.Groups[1].Value);
          }

          // Parse: "Total Orders:           12739"
          var ordersMatch = Regex.Match(line, @"Total Orders:\s+(\d+)");
          if (ordersMatch.Success)
          {
            result.TotalOrders = int.Parse(ordersMatch.Groups[1].Value);
          }

          // Parse: "Elapsed Time:            50.0 sec"
          var timeMatch = Regex.Match(line, @"Elapsed Time:\s+([\d.]+)\s+sec");
          if (timeMatch.Success)
          {
            result.ElapsedTime = double.Parse(timeMatch.Groups[1].Value);
          }

          // Parse: "  Total (avg):            0.026 sec"
          var avgRtMatch = Regex.Match(line, @"Total \(avg\):\s+([\d.]+)\s+sec");
          if (avgRtMatch.Success)
          {
            result.AvgRt = double.Parse(avgRtMatch.Groups[1].Value) * 1000; // Convert to ms
          }

          // Parse: "  Rollbacks:               276 ( 1.1%)"
          var rollbackMatch = Regex.Match(line, @"Rollbacks:\s+\d+\s+\(\s*([\d.]+)%\)");
          if (rollbackMatch.Success)
          {
            result.RollbackPct = double.Parse(rollbackMatch.Groups[1].Value);
          }

          // Parse analytics response times
          // "  GetMembershipAnalytics:      10 operations, avg RT: 0.125 sec"
          var membershipMatch = Regex.Match(line, @"GetMembershipAnalytics:\s+\d+\s+operations,\s+avg RT:\s+([\d.]+)\s+sec");
          if (membershipMatch.Success)
          {
            result.MembershipAnalyticsRt = double.Parse(membershipMatch.Groups[1].Value);
          }

          var newCustomerMatch = Regex.Match(line, @"GetNewCustomerAnalytics:\s+\d+\s+operations,\s+avg RT:\s+([\d.]+)\s+sec");
          if (newCustomerMatch.Success)
          {
            result.NewCustomerAnalyticsRt = double.Parse(newCustomerMatch.Groups[1].Value);
          }

          var reviewMatch = Regex.Match(line, @"GetReviewAnalytics:\s+\d+\s+operations,\s+avg RT:\s+([\d.]+)\s+sec");
          if (reviewMatch.Success)
          {
            result.ReviewAnalyticsRt = double.Parse(reviewMatch.Groups[1].Value);
          }

          var pricePointMatch = Regex.Match(line, @"GetPricePointAnalytics:\s+\d+\s+operations,\s+avg RT:\s+([\d.]+)\s+sec");
          if (pricePointMatch.Success)
          {
            result.PricePointAnalyticsRt = double.Parse(pricePointMatch.Groups[1].Value);
          }

          var inventoryMatch = Regex.Match(line, @"GetInventoryAnalytics:\s+\d+\s+operations,\s+avg RT:\s+([\d.]+)\s+sec");
          if (inventoryMatch.Success)
          {
            result.InventoryAnalyticsRt = double.Parse(inventoryMatch.Groups[1].Value);
          }

          // Parse manager operation response times
          // "  AddProduct:              12 operations, 120 products added, avg RT: 0.034 sec"
          var addProductMatch = Regex.Match(line, @"AddProduct:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (addProductMatch.Success)
          {
            result.AddProductRt = double.Parse(addProductMatch.Groups[1].Value);
          }

          var removeByProductMatch = Regex.Match(line, @"RemoveReviewByProduct:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (removeByProductMatch.Success)
          {
            result.RemoveReviewByProductRt = double.Parse(removeByProductMatch.Groups[1].Value);
          }

          var removeUnhelpfulMatch = Regex.Match(line, @"RemoveUnhelpfulReviews:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (removeUnhelpfulMatch.Success)
          {
            result.RemoveUnhelpfulReviewsRt = double.Parse(removeUnhelpfulMatch.Groups[1].Value);
          }

          var removeByDateMatch = Regex.Match(line, @"RemoveReviewsByDate:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (removeByDateMatch.Success)
          {
            result.RemoveReviewsByDateRt = double.Parse(removeByDateMatch.Groups[1].Value);
          }

          var adjustPricesMatch = Regex.Match(line, @"AdjustPrices:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (adjustPricesMatch.Success)
          {
            result.AdjustPricesRt = double.Parse(adjustPricesMatch.Groups[1].Value);
          }

          var bulkPriceMatch = Regex.Match(line, @"BulkPriceAdjustment:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (bulkPriceMatch.Success)
          {
            result.BulkPriceAdjustmentRt = double.Parse(bulkPriceMatch.Groups[1].Value);
          }

          var markSpecialsMatch = Regex.Match(line, @"MarkSpecials:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (markSpecialsMatch.Success)
          {
            result.MarkSpecialsRt = double.Parse(markSpecialsMatch.Groups[1].Value);
          }

          var expireMatch = Regex.Match(line, @"ExpireMemberships:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (expireMatch.Success)
          {
            result.ExpireMembershipsRt = double.Parse(expireMatch.Groups[1].Value);
          }

          var purgeMatch = Regex.Match(line, @"PurgeOldOrders:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (purgeMatch.Success)
          {
            result.PurgeOldOrdersRt = double.Parse(purgeMatch.Groups[1].Value);
          }

          var upgradeMatch = Regex.Match(line, @"UpgradeMembership:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (upgradeMatch.Success)
          {
            result.UpgradeMembershipRt = double.Parse(upgradeMatch.Groups[1].Value);
          }

          var promoMatch = Regex.Match(line, @"PromotionalMembership:\s+\d+\s+operations,.*?avg RT:\s+([\d.]+)\s+sec");
          if (promoMatch.Success)
          {
            result.PromotionalMembershipRt = double.Parse(promoMatch.Groups[1].Value);
          }
        }

        // Only return if we got at least OPM
        if (result.Opm > 0)
        {
          return result;
        }
      }
      catch (Exception ex)
      {
        Console.WriteLine($"Error parsing {logFile}: {ex.Message}");
      }

      return null;
    }

    public static void PrintComparisonTable(List<DatabaseResults> results)
    {
      if (results.Count == 0)
      {
        Console.WriteLine("No results to compare.");
        return;
      }

      Console.WriteLine("\n========================================================================");
      Console.WriteLine("                    PERFORMANCE COMPARISON");
      Console.WriteLine("========================================================================\n");

      // Main performance metrics
      Console.WriteLine("Database Performance:");
      Console.WriteLine("───────────────────────────────────────────────────────────────────────");
      Console.WriteLine("Database            Hostname           OPM    Avg RT  Rollback%  Orders");
      Console.WriteLine("───────────────────────────────────────────────────────────────────────");


      foreach (var r in results.OrderByDescending(x => x.Opm))
      {
        // Extract hostname (before first dot), then truncate to 15 chars if needed
        string shortHostname = r.Hostname.Split('.')[0];
        if (shortHostname.Length > 15)
          shortHostname = shortHostname.Substring(0, 15);

        Console.WriteLine($"{r.DbType,-18} {shortHostname,-15}  {r.Opm,6:N0}  {r.AvgRt,6:F1}ms    {r.RollbackPct,5:F1}%  {r.TotalOrders,7:N0}");
      }
      Console.WriteLine("───────────────────────────────────────────────────────────────────────");

      // Analytics performance (if any database has analytics)
      bool hasAnalytics = results.Any(r => r.MembershipAnalyticsRt > 0 || r.NewCustomerAnalyticsRt > 0 ||
                                          r.ReviewAnalyticsRt > 0 || r.PricePointAnalyticsRt > 0 ||
                                          r.InventoryAnalyticsRt > 0);

      if (hasAnalytics)
      {
        Console.WriteLine("\nAnalytics Performance (avg RT in seconds):");
        Console.WriteLine("─────────────────────────────────────────────────────────────────────────");
        Console.WriteLine("Database            Membership  NewCust  Review  Price  Inventory   Total");
        Console.WriteLine("─────────────────────────────────────────────────────────────────────────");

        foreach (var r in results)
        {
          string membership = r.MembershipAnalyticsRt > 0 ? $"{r.MembershipAnalyticsRt:F3}" : "  -  ";
          string newCust = r.NewCustomerAnalyticsRt > 0 ? $"{r.NewCustomerAnalyticsRt:F3}" : "  -  ";
          string review = r.ReviewAnalyticsRt > 0 ? $"{r.ReviewAnalyticsRt:F3}" : "  -  ";
          string price = r.PricePointAnalyticsRt > 0 ? $"{r.PricePointAnalyticsRt:F3}" : "  -  ";
          string inventory = r.InventoryAnalyticsRt > 0 ? $"{r.InventoryAnalyticsRt:F3}" : "  -  ";

          // Calculate total of all analytics operations
          double total = r.MembershipAnalyticsRt + r.NewCustomerAnalyticsRt + r.ReviewAnalyticsRt +
                        r.PricePointAnalyticsRt + r.InventoryAnalyticsRt;
          string totalStr = total > 0 ? $"{total:F3}" : "  -  ";

          Console.WriteLine($"{r.DbType,-18} {membership,10}  {newCust,7}  {review,6}   {price,5} {inventory,9}   {totalStr,6}");
        }
        Console.WriteLine("─────────────────────────────────────────────────────────────────────────");
      }

      // Manager operations performance (if any database has managers enabled)
      bool hasManagers = results.Any(r => r.AddProductRt > 0 || r.RemoveReviewByProductRt > 0 ||
                                         r.RemoveUnhelpfulReviewsRt > 0 || r.RemoveReviewsByDateRt > 0 ||
                                         r.AdjustPricesRt > 0 || r.BulkPriceAdjustmentRt > 0 ||
                                         r.MarkSpecialsRt > 0 || r.ExpireMembershipsRt > 0 ||
                                         r.PurgeOldOrdersRt > 0 || r.UpgradeMembershipRt > 0 ||
                                         r.PromotionalMembershipRt > 0);

      if (hasManagers)
      {
        Console.WriteLine("\nManager Operations Performance (avg RT in seconds):");
        Console.WriteLine("────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────");
        Console.WriteLine("Database          AddProd  RmvByProd  RmvUnhlp  RmvByDate  AdjPrice  BulkPrc  MrkSpecl  ExpireMbr  PurgeOrd  UpgradeMbr  PromoMbr  Total");
        Console.WriteLine("────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────");

        foreach (var r in results)
        {
          string addProd = r.AddProductRt > 0 ? $"{r.AddProductRt:F3}" : "  -  ";
          string rmvProd = r.RemoveReviewByProductRt > 0 ? $"{r.RemoveReviewByProductRt:F3}" : "  -  ";
          string rmvUnhlp = r.RemoveUnhelpfulReviewsRt > 0 ? $"{r.RemoveUnhelpfulReviewsRt:F3}" : "  -  ";
          string rmvDate = r.RemoveReviewsByDateRt > 0 ? $"{r.RemoveReviewsByDateRt:F3}" : "  -  ";
          string adjPrice = r.AdjustPricesRt > 0 ? $"{r.AdjustPricesRt:F3}" : "  -  ";
          string bulkPrc = r.BulkPriceAdjustmentRt > 0 ? $"{r.BulkPriceAdjustmentRt:F3}" : "  -  ";
          string mrkSpec = r.MarkSpecialsRt > 0 ? $"{r.MarkSpecialsRt:F3}" : "  -  ";
          string expire = r.ExpireMembershipsRt > 0 ? $"{r.ExpireMembershipsRt:F3}" : "  -  ";
          string purge = r.PurgeOldOrdersRt > 0 ? $"{r.PurgeOldOrdersRt:F3}" : "  -  ";
          string upgrade = r.UpgradeMembershipRt > 0 ? $"{r.UpgradeMembershipRt:F3}" : "  -  ";
          string promo = r.PromotionalMembershipRt > 0 ? $"{r.PromotionalMembershipRt:F3}" : "  -  ";

          // Calculate total of all manager operations
          double total = r.AddProductRt + r.RemoveReviewByProductRt + r.RemoveUnhelpfulReviewsRt +
                        r.RemoveReviewsByDateRt + r.AdjustPricesRt + r.BulkPriceAdjustmentRt +
                        r.MarkSpecialsRt + r.ExpireMembershipsRt + r.PurgeOldOrdersRt +
                        r.UpgradeMembershipRt + r.PromotionalMembershipRt;
          string totalStr = total > 0 ? $"{total:F3}" : "  -  ";

          Console.WriteLine($"{r.DbType,-16}  {addProd,7}  {rmvProd,9}  {rmvUnhlp,8}  {rmvDate,9}  {adjPrice,8}  {bulkPrc,7}  {mrkSpec,8}  {expire,9}  {purge,8}  {upgrade,9}  {promo,8}  {totalStr,6}");
        }
        Console.WriteLine("────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────");
      }

      Console.WriteLine("========================================================================\n");
    }
  }
}
