/*
 * DVD Store 3.6 Analytics Thread - ds36xanalytics.cs
 *
 * Copyright (C) 2026 Red Hat, Inc. <dyeisley@redhat.com>
 *  Generated by claude-code.
 *
 * Implements analytics threads for DVD Store 3.6 benchmark
 * Performs periodic analytics queries: membership analytics, product analytics, review analytics
 *
 * Analytics operations run on a timer and do NOT count toward OPM (Orders Per Minute) metric
 * Analytics thread runs independently from manager operations thread
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA  */

namespace ds2xdriver
{
  /// <summary>
  /// Analytics class: performs periodic analytics queries on DVD Store database
  /// Runs in separate thread from manager operations for non-blocking analytics
  /// </summary>
  class Analytics
  {
    int AnalyticsId;
    ds2Interface ds2interface;
    public int target_server_id = 0;
    int target_store = 1;

    // Analytics counters (for statistics)
    public int n_membership_analytics = 0;
    public double rt_membership_analytics = 0.0;

    // Analytics timing
    private DateTime test_start_time;
    private DateTime last_analytics_print_time;

    // Baseline analytics for delta tracking
    private Dictionary<int, (long orders, decimal revenue)> baseline_analytics = new Dictionary<int, (long, decimal)>();

    //
    //-------------------------------------------------------------------------------------------------
    //
    public Analytics(int analyticsid, int server_id, int target_store_num)
    {
      AnalyticsId = analyticsid;
      target_server_id = server_id;
      target_store = target_store_num;
    }

    //
    //-------------------------------------------------------------------------------------------------
    //
    public void RunAnalytics()
    {
      Thread.CurrentThread.Name = "Analytics" + AnalyticsId;
      Console.WriteLine("Thread {0}: created for Analytics {1} (Store {2})", Thread.CurrentThread.Name, AnalyticsId, target_store);

      int analytics_interval_seconds = Controller.analytics_interval * 60;

      // Create database interface
      ds2interface = new ds2Interface(AnalyticsId + 20000, Controller.target_servers[target_server_id], target_store);

      // Connect to database
      if (!ds2interface.ds2connect())
      {
        Console.WriteLine("Thread {0}: can't connect to {1}; exiting", Thread.CurrentThread.Name, Controller.target_servers[target_server_id]);
        return;
      }
      Console.WriteLine("Thread {0}: connected to {1}", Thread.CurrentThread.Name, Controller.target_servers[target_server_id]);

      // Wait for Controller to signal start
      while (!Controller.Start)
        Thread.Sleep(100);

      // Record test start time for analytics timing
      test_start_time = DateTime.Now;
      last_analytics_print_time = test_start_time;

      // Capture baseline analytics at test start (if membership analytics enabled)
      if (Controller.analytics_interval > 0 && Controller.enable_membership_analytics)
      {
        try
        {
          double rt_baseline = 0.0;
          var baselineData = ds2interface.ds36getmembershipanalytics(ref rt_baseline);
          if (baselineData != null && baselineData.Count > 0)
          {
            foreach (var row in baselineData)
            {
              int tierKey = row.MembershipType ?? -1;  // Use -1 for NULL tier
              baseline_analytics[tierKey] = (row.TotalOrders, row.TotalRevenue);
            }
            Console.WriteLine($"Thread {Thread.CurrentThread.Name}: Membership Analytics baseline captured at test start ({DateTime.Now:HH:mm:ss})");
          }
        }
        catch (Exception e)
        {
          Console.WriteLine("Thread {0}: Baseline analytics capture error: {1}", Thread.CurrentThread.Name, e.Message);
          if (e.Message.Contains("Fatal error") || e.Message.Contains("Connection must be valid and open"))
          {
            Console.WriteLine("Thread {0}: Fatal connection error during baseline capture, exiting analytics thread", Thread.CurrentThread.Name);
            ds2interface.ds2close();
            Console.WriteLine("Thread {0}: Analytics thread exiting", Thread.CurrentThread.Name);
            return;
          }
        }
      }

      // Analytics loop: run until Controller signals End
      while (!Controller.End)
      {
        // Sleep for the analytics interval in 1-second increments (allows fast shutdown)
        for (int i = 0; i < analytics_interval_seconds && !Controller.End; i++)
        {
          Thread.Sleep(1000);
        }

	// It might be time to end after sleeping
        if (Controller.End)
          break;

        // Time-based membership analytics
        if (Controller.analytics_interval > 0 && Controller.enable_membership_analytics)
        {
          double time_since_last_analytics = (DateTime.Now - last_analytics_print_time).TotalSeconds;

	  //Console.WriteLine($"Time since last analytics: {time_since_last_analytics:F2} seconds");

          if (time_since_last_analytics >= analytics_interval_seconds)
          {
            // Set timestamp now to maintain fixed interval regardless of query duration
            last_analytics_print_time = DateTime.Now;

            try
            {
              double rt_analytics = 0.0;
              var analyticsData = ds2interface.ds36getmembershipanalytics(ref rt_analytics);

              if (analyticsData != null && analyticsData.Count > 0)
              {
                Console.WriteLine("\n=====================================================================================================");
                Console.WriteLine($"Membership Analytics (Store {target_store}) - Delta since baseline");
                Console.WriteLine("=====================================================================================================");
                Console.WriteLine("Tier    Active Members    Expired    New Orders  New Revenue     Rev/Order   Rev/Member    Ord/Member");
                Console.WriteLine("-----   --------------    -------    ----------  -------------   ---------   -----------   ----------");

                // Sort: Tier 3 → 2 → 1 → NULL (descending, NULL last)
                var sortedData = analyticsData.OrderByDescending(row => row.MembershipType ?? int.MinValue);

                foreach (var row in sortedData)
                {
                  string tier = row.MembershipType.HasValue ? row.MembershipType.Value.ToString().PadLeft(4) : " N/A";

                  // Calculate deltas
                  long deltaOrders = 0;
                  decimal deltaRevenue = 0;
                  int tierKey = row.MembershipType ?? -1;  // Use -1 for NULL tier
                  if (baseline_analytics.TryGetValue(tierKey, out var baseline))
                  {
                    deltaOrders = row.TotalOrders - baseline.orders;
                    deltaRevenue = row.TotalRevenue - baseline.revenue;
                  }

                  // Calculate derived metrics (from deltas)
                  decimal revenuePerOrder = deltaOrders > 0 ? deltaRevenue / deltaOrders : 0;
                  decimal revenuePerMember = row.ActiveMemberCount > 0 ? deltaRevenue / row.ActiveMemberCount : 0;
                  decimal ordersPerMember = row.ActiveMemberCount > 0 ? (decimal)deltaOrders / row.ActiveMemberCount : 0;

                  Console.WriteLine($"{tier}    {row.ActiveMemberCount,14:N0}    {row.ExpiredMemberCount,7:N0}    {deltaOrders,10:N0}  {deltaRevenue,13:C2}   {revenuePerOrder,9:C2}   {revenuePerMember,11:C2}   {ordersPerMember,10:F2}");
                }

                Console.WriteLine("=====================================================================================================\n");
              }

              n_membership_analytics++;
              rt_membership_analytics += rt_analytics;
            }
            catch (Exception e)
            {
              Console.WriteLine("Thread {0}: GetMembershipAnalytics error: {1}", Thread.CurrentThread.Name, e.Message);
              if (e.Message.Contains("Fatal error") || e.Message.Contains("Connection must be valid and open"))
              {
                Console.WriteLine("Thread {0}: Fatal connection error detected, exiting analytics thread", Thread.CurrentThread.Name);
                break;
              }
            }
          }
        }
      }

      // Close database connection
      ds2interface.ds2close();

      // Print statistics
      if (n_membership_analytics > 0)
      {
        Console.WriteLine("\n========== Analytics Statistics (Store {0}) ==========", target_store);
        Console.WriteLine("  GetMembershipAnalytics:  {0,6} operations, avg RT: {1:F3} sec",
                          n_membership_analytics, rt_membership_analytics / n_membership_analytics);
        Console.WriteLine("=======================================================\n");
      }

      Console.WriteLine("Thread {0}: Analytics thread exiting", Thread.CurrentThread.Name);
    }

  } // end class Analytics
} // end namespace ds2xdriver
