/*
 * DVD Store 3.6 Manager Thread - ds36xmanager.cs
 *
 * Copyright (C) 2026 Red Hat, Inc. <dyeisley@redhat.com>
 *  Generated by claude-code.
 *
 * Implements manager/admin threads for DVD Store 3.6 benchmark
 * Performs periodic maintenance operations: add inventory, remove reviews, adjust prices, update specials
 *
 * Manager operations run on a timer and do NOT count toward OPM (Orders Per Minute) metric
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA  */

using System;
using System.Threading;
using System.Diagnostics;

namespace ds2xdriver
{
  /// <summary>
  /// Manager class: performs periodic admin/maintenance operations on DVD Store database
  /// </summary>
  class Manager
  {
    int ManagerId;
    ds2Interface ds2interface;
    public int target_server_id = 0;
    int target_store = 1;

    // Operation counters (for statistics)
    public int n_add_product = 0;
    public int n_remove_review_by_product = 0;
    public int n_remove_unhelpful_reviews = 0;
    public int n_adjust_prices = 0;
    public int n_mark_specials = 0;
    public int n_products_added = 0;
    public int n_reviews_removed_by_product = 0;
    public int n_reviews_removed_unhelpful = 0;
    public int n_products_price_changed = 0;
    public int n_products_special_changed = 0;
    public double rt_add_product = 0.0;
    public double rt_remove_review_by_product = 0.0;
    public double rt_remove_unhelpful_reviews = 0.0;
    public double rt_adjust_prices = 0.0;
    public double rt_mark_specials = 0.0;

    //
    //-------------------------------------------------------------------------------------------------
    //
    public Manager(int managerid, int server_id, int target_store_num)
    {
      ManagerId = managerid;
      target_server_id = server_id;
      target_store = target_store_num;
      // Console.WriteLine("Manager {0} created for store {1} on server {2}", managerid, target_store, server_id);
    }

    //
    //-------------------------------------------------------------------------------------------------
    //
    string CreateActor()
    {
      return (fake_actor_data.actor_firstnames[Random.Shared.Next(fake_actor_data.firstname_pool_size)] + " " +
              fake_actor_data.actor_lastnames[Random.Shared.Next(fake_actor_data.lastname_pool_size)]);
    }

    //
    //-------------------------------------------------------------------------------------------------
    //
    string CreateTitle()
    {
      return (fake_title_data.movie_titles[Random.Shared.Next(fake_title_data.title_pool_size)] + " " +
              fake_title_data.movie_titles[Random.Shared.Next(fake_title_data.title_pool_size)]);
    }

    //
    //-------------------------------------------------------------------------------------------------
    //
    public int GetSkewedProductId(int maxProduct)
    {
      int popularInterval = 10000;
      int weightBoost = 9;

      int popularCount = maxProduct / popularInterval;
      long totalWeight = (long)maxProduct + ((long)popularCount * weightBoost);
      long roll = (long)(Random.Shared.NextDouble() * totalWeight);

      long blockSize = popularInterval + weightBoost;
      long blockCount = roll / blockSize;
      long offsetInBlock = roll % blockSize;

      if (offsetInBlock >= popularInterval)
      {
        return (int)(blockCount + 1) * popularInterval;
      }
      else
      {
        int rawId = (int)(blockCount * popularInterval + offsetInBlock) + 1;
        return rawId > maxProduct ? maxProduct : rawId;
      }
    }

    //
    //-------------------------------------------------------------------------------------------------
    //
    public void RunManager()
    {
      Thread.CurrentThread.Name = "Manager" + ManagerId;
      Console.WriteLine("Thread {0}: created for Manager {1} (Store {2})", Thread.CurrentThread.Name, ManagerId, target_store);

      // Create database interface
      ds2interface = new ds2Interface(ManagerId + 10000, Controller.target_servers[target_server_id], target_store);

      // Connect to database
      if (!ds2interface.ds2connect())
      {
        Console.WriteLine("Thread {0}: can't connect to {1}; exiting", Thread.CurrentThread.Name, Controller.target_servers[target_server_id]);
        return;
      }
      Console.WriteLine("Thread {0}: connected to {1}", Thread.CurrentThread.Name, Controller.target_servers[target_server_id]);

      // Wait for Controller to signal start
      while (!Controller.Start) Thread.Sleep(100);

      Console.WriteLine("Thread {0}: Manager thread started", Thread.CurrentThread.Name);

      // Manager loop: run until Controller signals End
      while (!Controller.End)
      {
        // Sleep for the manager interval
        Thread.Sleep(Controller.manager_interval * 1000);

        if (Controller.End) break;

        // Randomly select operation based on percentages
        int total_pct = Controller.manager_add_product_pct + Controller.manager_delete_review_pct +
                        Controller.manager_update_price_pct + Controller.manager_update_special_pct;

        if (total_pct == 0)
        {
          // No operations configured, just sleep
          continue;
        }

        int roll = Random.Shared.Next(total_pct);
        double rt = 0.0;
        int rows_affected = 0;

        try
        {
          if (roll < Controller.manager_add_product_pct)
          {
            // AddNewInventoryProduct (40% default)
            int new_category_in = Random.Shared.Next(1, GlobalConstants.MAX_CATEGORY + 1);
            string new_actor_in = CreateActor();
            string new_title_in = CreateTitle();
            decimal price_in = Random.Shared.Next(6, 21) + 0.01m;  // Prices from 6.01 to 20.01
            int initial_stock_in = Random.Shared.Next(1, 500);

            int newproduct_id = 0;
            if (ds2interface.ds2newproduct(new_category_in, new_title_in, new_actor_in, price_in, initial_stock_in, ref newproduct_id, ref rt))
            {
              n_add_product++;
              rt_add_product += rt;
              if (newproduct_id > 0)
              {
                n_products_added++;
              }
              // Update max_product for this store if needed
              if (newproduct_id > Controller.max_product[target_store - 1])
              {
                Controller.max_product[target_store - 1] = newproduct_id;
              }
              //Console.WriteLine("Thread {0}: Added product {1}: {2} - {3}", Thread.CurrentThread.Name, newproduct_id, new_title_in, new_actor_in);
            }
          }
          else if (roll < Controller.manager_add_product_pct + Controller.manager_delete_review_pct)
          {
            // RemoveReview - 50% by product, 50% unhelpful globally (20% default)
            if (Random.Shared.Next(2) == 0)
            {
              // RemoveReviewByProduct - deletes 1 review, returns its ID (0 if none deleted)
              int prod_id = GetSkewedProductId(Controller.max_product[target_store - 1]);
              int deleted_review_id = ds2interface.ds36removereviewbyproduct(prod_id, ref rt);
              n_remove_review_by_product++;
              rt_remove_review_by_product += rt;
              if (deleted_review_id > 0)
              {
                n_reviews_removed_by_product++;
                //Console.WriteLine("Thread {0}: Removed review {1} for product {2}", Thread.CurrentThread.Name, deleted_review_id, prod_id);
              }
            }
            else
            {
              // RemoveUnhelpfulReviews
              int batch_size = Random.Shared.Next(Controller.manager_review_batch_size_min, Controller.manager_review_batch_size_max + 1);
              rows_affected = ds2interface.ds36removeunhelpfulreviews(batch_size, ref rt);
              n_remove_unhelpful_reviews++;
              n_reviews_removed_unhelpful += rows_affected;
              rt_remove_unhelpful_reviews += rt;
              //Console.WriteLine("Thread {0}: Removed {1} unhelpful reviews", Thread.CurrentThread.Name, rows_affected);
            }
          }
          else if (roll < Controller.manager_add_product_pct + Controller.manager_delete_review_pct + Controller.manager_update_price_pct)
          {
            // AdjustPrices (25% default)
            int prod_id = GetSkewedProductId(Controller.max_product[target_store - 1]);
            rows_affected = ds2interface.ds36adjustprices(prod_id, ref rt);
            n_adjust_prices++;
            n_products_price_changed += rows_affected;
            rt_adjust_prices += rt;
            //Console.WriteLine("Thread {0}: Adjusted price for product {1}, rows affected: {2}", Thread.CurrentThread.Name, prod_id, rows_affected);
          }
          else
          {
            // MarkSpecials (15% default)
            int prod_id = GetSkewedProductId(Controller.max_product[target_store - 1]);
            rows_affected = ds2interface.ds36markspecials(prod_id, ref rt);
            n_mark_specials++;
            n_products_special_changed += rows_affected;
            rt_mark_specials += rt;
            //Console.WriteLine("Thread {0}: Toggled special for product {1}, rows affected: {2}", Thread.CurrentThread.Name, prod_id, rows_affected);
          }
        }
        catch (Exception e)
        {
          Console.WriteLine("Thread {0}: Manager operation error: {1}", Thread.CurrentThread.Name, e.Message);
        }
      }

      // Close database connection
      ds2interface.ds2close();

      // Print statistics
      int total_operations = n_add_product + n_remove_review_by_product + n_remove_unhelpful_reviews +
                             n_adjust_prices + n_mark_specials;
      int total_review_ops = n_remove_review_by_product + n_remove_unhelpful_reviews;
      double total_review_rt = rt_remove_review_by_product + rt_remove_unhelpful_reviews;
      Console.WriteLine("\n========== Manager Thread {0} Statistics (Store {1}) ==========", ManagerId, target_store);
      Console.WriteLine("Total Operations: {0}", total_operations);
      Console.WriteLine("  AddProduct:              {0,6} operations, {1,6} products added{2}",
                        n_add_product, n_products_added,
                        n_add_product > 0 ? string.Format(", avg RT: {0:F3} sec", rt_add_product / n_add_product) : "");
      Console.WriteLine("  RemoveReviewByProduct:   {0,6} operations, {1,6} reviews removed{2}",
                        n_remove_review_by_product, n_reviews_removed_by_product,
                        n_remove_review_by_product > 0 ? string.Format(", avg RT: {0:F3} sec", rt_remove_review_by_product / n_remove_review_by_product) : "");
      Console.WriteLine("  RemoveUnhelpfulReviews:  {0,6} operations, {1,6} reviews removed{2}",
                        n_remove_unhelpful_reviews, n_reviews_removed_unhelpful,
                        n_remove_unhelpful_reviews > 0 ? string.Format(", avg RT: {0:F3} sec", rt_remove_unhelpful_reviews / n_remove_unhelpful_reviews) : "");
      int total_reviews_removed = n_reviews_removed_by_product + n_reviews_removed_unhelpful;
      Console.WriteLine("  RemoveReview (combined): {0,6} operations, {1,6} reviews removed{2}",
                        total_review_ops, total_reviews_removed,
                        total_review_ops > 0 ? string.Format(", avg RT: {0:F3} sec", total_review_rt / total_review_ops) : "");
      Console.WriteLine("  AdjustPrices:            {0,6} operations, {1,6} products changed{2}",
                        n_adjust_prices, n_products_price_changed,
                        n_adjust_prices > 0 ? string.Format(", avg RT: {0:F3} sec", rt_adjust_prices / n_adjust_prices) : "");
      Console.WriteLine("  MarkSpecials:            {0,6} operations, {1,6} products changed{2}",
                        n_mark_specials, n_products_special_changed,
                        n_mark_specials > 0 ? string.Format(", avg RT: {0:F3} sec", rt_mark_specials / n_mark_specials) : "");
      Console.WriteLine("================================================================\n");

      Console.WriteLine("Thread {0}: Manager thread exiting", Thread.CurrentThread.Name);
    }

  } // end class Manager
} // end namespace ds2xdriver
