
<?php
/*
 * DVD Store Get Membership Status PHP Page - dsgetmembershipstatus.php
 *
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Check customer membership status using get_membership_status stored procedure
 *
 * Generated by Claude Code (Anthropic)
 *
 * Last Updated 7/29/26
 *
 * Support for PHP 8 and PostgreSQL
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

include("dscommon.inc");

ds_html_header("Membership Status");

$customerid = $_REQUEST["customerid"];
$storenum = isset($_REQUEST["storenum"]) ? $_REQUEST["storenum"] : 1;

if (!($link_id=pg_pconnect($connstr))) die(pg_last_error());

// Call get_membership_status stored procedure
$membership_query = "SELECT * FROM get_membership_status$storenum($customerid::INT)";
$result = pg_query($link_id, $membership_query);

if (!$result) {
  die("get_membership_status failed: " . pg_last_error($link_id));
}

$row = pg_fetch_row($result);
if ($row) {
  $membership_level = $row[0];
  $is_expired = $row[1];
} else {
  $membership_level = 0;
  $is_expired = 0;
}
pg_free_result($result);

// Display membership status for humans
if ($membership_level > 0) {
  $tier_names = ['', 'Bronze', 'Silver', 'Gold'];
  $tier_name = $tier_names[$membership_level];
  if ($is_expired == 1) {
    echo "<H2>Your membership: $tier_name (EXPIRED)</H2>\n";
    echo "<P>Your membership has expired. Please renew to continue enjoying member benefits.</P>\n";
  } else {
    echo "<H2>Your membership: $tier_name (Active)</H2>\n";
    echo "<P>Thank you for being a valued member!</P>\n";
  }
} else {
  echo "<H2>Not a premium member</H2>\n";
  echo "<P>You are currently browsing as a regular customer.</P>\n";
}

// Hidden fields for C# driver to parse
echo "<INPUT TYPE=HIDDEN NAME=membership_level VALUE=$membership_level>\n";
echo "<INPUT TYPE=HIDDEN NAME=is_expired VALUE=$is_expired>\n";

// Show appropriate button based on status
if ($membership_level > 0 && $is_expired == 1) {
  // Expired member - show Renew and Browse buttons
  echo "<FORM ACTION='./dsrenewmembership.php' METHOD=GET>\n";
  echo "<INPUT TYPE=HIDDEN NAME=customerid VALUE=$customerid>\n";
  echo "<INPUT TYPE=HIDDEN NAME=storenum VALUE=$storenum>\n";
  echo "<INPUT TYPE=HIDDEN NAME=membership_level VALUE=$membership_level>\n";
  echo "<INPUT TYPE=SUBMIT VALUE='Renew Membership'>\n";
  echo "</FORM>\n";
  echo "<BR>\n";

  echo "<FORM ACTION='./dsbrowse.php' METHOD=GET>\n";
  echo "<INPUT TYPE=HIDDEN NAME=customerid VALUE=$customerid>\n";
  echo "<INPUT TYPE=HIDDEN NAME=storenum VALUE=$storenum>\n";
  echo "<INPUT TYPE=HIDDEN NAME=membership_level VALUE=0>\n";
  echo "<INPUT TYPE=SUBMIT VALUE='Browse Without Renewing'>\n";
  echo "</FORM>\n";
} else if ($membership_level == 0) {
  // Not a member - show Signup and Browse buttons
  echo "<FORM ACTION='./dsnewmember.php' METHOD=GET>\n";
  echo "<INPUT TYPE=HIDDEN NAME=customerid VALUE=$customerid>\n";
  echo "<INPUT TYPE=HIDDEN NAME=storenum VALUE=$storenum>\n";
  echo "<INPUT TYPE=SUBMIT VALUE='Premium Member Signup'>\n";
  echo "</FORM>\n";
  echo "<BR>\n";

  echo "<FORM ACTION='./dsbrowse.php' METHOD=GET>\n";
  echo "<INPUT TYPE=HIDDEN NAME=customerid VALUE=$customerid>\n";
  echo "<INPUT TYPE=HIDDEN NAME=storenum VALUE=$storenum>\n";
  echo "<INPUT TYPE=HIDDEN NAME=membership_level VALUE=0>\n";
  echo "<INPUT TYPE=SUBMIT VALUE='Browse Without Membership'>\n";
  echo "</FORM>\n";
} else {
  // Active member - show Browse button with membership_level
  echo "<FORM ACTION='./dsbrowse.php' METHOD=GET>\n";
  echo "<INPUT TYPE=HIDDEN NAME=customerid VALUE=$customerid>\n";
  echo "<INPUT TYPE=HIDDEN NAME=storenum VALUE=$storenum>\n";
  echo "<INPUT TYPE=HIDDEN NAME=membership_level VALUE=$membership_level>\n";
  echo "<INPUT TYPE=SUBMIT VALUE='Start Shopping'>\n";
  echo "</FORM>\n";
}

pg_close($link_id);
ds_html_footer();
?>
