
<?php
/*
 * DVD Store Get Row Count PHP Page - dsgetrowcount.php
 *
 * Copyright (C) 2025 Red Hat, Inc.
 *
 * Returns row count for a specified table
 *
 * Generated by Claude Code (Anthropic)
 *
 * Last Updated 7/29/26
 *
 * Support for PHP 8 and PostgreSQL
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

include("dscommon.inc");

ds_html_header("Get Row Count");

$tablename = $_REQUEST["tablename"];
$storenum = isset($_REQUEST["storenum"]) ? $_REQUEST["storenum"] : 1;

if (empty($tablename))
  {
  echo "<H2>Error: No table name specified</H2>\n";
  ds_html_footer();
  exit;
  }

if (!($link_id=pg_connect($connstr))) die(pg_last_error());

// Execute COUNT(*) query
$query = "SELECT COUNT(*) FROM $tablename;";
$result = pg_query($link_id,$query);

if (!$result)
  {
  echo "<H2>Error executing query: " . pg_last_error($link_id) . "</H2>\n";
  pg_close($link_id);
  ds_html_footer();
  exit;
  }

$row = pg_fetch_row($result);
$rowcount = $row[0];
pg_free_result($result);
pg_close($link_id);

// Return rowcount in hidden input field (matches expected parse format from web driver)
echo "<INPUT TYPE=HIDDEN NAME=rowcount VALUE=$rowcount>\n";

ds_html_footer();
?>
