
<?php
/*
 * DVD Store Renew Membership PHP Page - dsrenewmembership.php
 *
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Renew customer membership using renew_membership stored procedure
 *
 * Generated by Claude Code (Anthropic)
 *
 * Last Updated 7/29/26
 *
 * Support for PHP 8 and PostgreSQL
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

include("dscommon.inc");

ds_html_header("Renew Membership");

$customerid = $_REQUEST["customerid"];
$storenum = isset($_REQUEST["storenum"]) ? $_REQUEST["storenum"] : 1;
$membership_level = isset($_REQUEST["membership_level"]) ? $_REQUEST["membership_level"] : 0;

if (!($link_id=pg_pconnect($connstr))) die(pg_last_error());

// Call renew_membership stored procedure
$renew_query = "SELECT * FROM renew_membership$storenum($customerid::INT)";
$result = pg_query($link_id, $renew_query);

if (!$result) {
  die("renew_membership failed: " . pg_last_error($link_id));
}

$row = pg_fetch_row($result);
if ($row) {
  $rows_affected = $row[0];
} else {
  $rows_affected = 0;
}
pg_free_result($result);

if ($rows_affected > 0) {
  echo "<H2>Membership Renewed Successfully!</H2>\n";
  echo "<P>Your membership has been extended for another year.</P>\n";
  echo "<P>Thank you for your continued support!</P>\n";
} else {
  echo "<H2>Membership Renewal Failed</H2>\n";
  echo "<P>We were unable to renew your membership. Please contact customer support.</P>\n";
}

// Hidden field for C# driver to parse
echo "<INPUT TYPE=HIDDEN NAME=rows_affected VALUE=$rows_affected>\n";

echo "<FORM ACTION='./dsbrowse.php' METHOD=GET>\n";
echo "<INPUT TYPE=HIDDEN NAME=customerid VALUE=$customerid>\n";
echo "<INPUT TYPE=HIDDEN NAME=storenum VALUE=$storenum>\n";
echo "<INPUT TYPE=HIDDEN NAME=membership_level VALUE=$membership_level>\n";
echo "<INPUT TYPE=SUBMIT VALUE='Start Shopping'>\n";
echo "</FORM>\n";

pg_close($link_id);
ds_html_footer();
?>
