#ifndef POPULAR_ACTORS_H
#define POPULAR_ACTORS_H

static const char* popular_actor_firstnames[] = {
    "Aaron", "Adam", "Adrien", "Aidan", "Al", "Alan", "Albert", "Alden", "Aldis", "Alec", "Alexander", "Alexandra",
    "Alfred", "Alicia", "Alison", "Allison", "Amanda", "Amandla", "Amber", "Amy", "Ana", "Andre", "Andrea", "Andrew",
    "Andy", "Angela", "Angelina", "Anjelica", "Ann", "Anna", "Anne", "Annette", "Anson", "Anthony", "Anton", "Antonio",
    "Antony", "Anya", "Aparna", "Archie", "Armie", "Arnold", "Aubrey", "Audrey", "Austin", "Ayo", "Barkhad", "Barry",
    "Ben", "Benedict", "Benicio", "Bette", "Bill", "Billy", "Bob", "Boyd", "Bradley", "Brendan", "Brenton", "Brian",
    "Brie", "Brittany", "Bruce", "Bryan", "Burt", "Cameron", "Carey", "Carl", "Carrie-Anne", "Cary", "Casey", "Cate",
    "Catherine", "Chace", "Channing", "Charles", "Charlie", "Charlize", "Chaske", "Chevy", "Chiwetel", "Chloe", "Chris",
    "Christian", "Christina", "Christoph", "Christopher", "Ciaran", "Cillian", "Claes", "Clark", "Clint", "Cloris",
    "Cobie", "Colby", "Colin", "Colman", "Connie", "Corey", "Courteney", "Craig", "Cuba", "Dakota", "Damian", "Dan",
    "Danai", "Dane", "Daniel", "Daniela", "Danielle", "Danny", "Dave", "David", "Demi", "Dennis", "Denzel", "Dermot",
    "Dev", "Diane", "Diego", "Djimon", "Dominic", "Dominique", "Don", "Donald", "Donnie", "Doris", "Doug", "Drew",
    "Dustin", "Dwayne", "Ed", "Eddie", "Edward", "Eiza", "Elijah", "Elisabeth", "Elizabeth", "Elle", "Ellen", "Elliot",
    "Elsie", "Emile", "Emilio", "Emily", "Emma", "Ernest", "Ernie", "Ethan", "Eugene", "Eva", "Evan", "Ewan", "Famke",
    "Finn", "Fionn", "Florence", "Forest", "Frances", "Frank", "Frankie", "Freddie", "Gael", "Gal", "Garrett", "Gary",
    "Geena", "Gemma", "Gene", "Geoffrey", "George", "Gerard", "Giancarlo", "Gillian", "Gina", "Ginnifer", "Glen", "Glenn",
    "Goldie", "Greta", "Gugu", "Gustaf", "Gwendoline", "Gwyneth", "Hailee", "Haley", "Halle", "Harris", "Harrison",
    "Harry", "Harvey", "Hayden", "Hayley", "Heath", "Helen", "Helena", "Henry", "Hilary", "Hiroyuki", "Holly", "Hugh",
    "Hugo", "Humphrey", "Ian", "Idris", "Iko", "Imelda", "Imogen", "Ingrid", "Ioan", "Issa", "Jack", "Jackie", "Jacob",
    "Jaden", "Jahi", "Jai", "Jaimie", "Jake", "James", "Jamie", "Jane", "Janet", "Jason", "Javier", "Jean", "Jeff",
    "Jeffrey", "Jena", "Jenna", "Jennifer", "Jeremy", "Jerome", "Jerry", "Jesse", "Jessica", "Jet", "Jim", "J.K.",
    "Joaquin", "Jodie", "Joe", "Joel", "John", "Johnny", "Jon", "Jonah", "Jonathan", "Jordan", "Joseph", "Josh", "Judd",
    "Jude", "Judi", "Judy", "Julia", "Julianne", "Juliette", "Juno", "Jurnee", "Justice", "Justin", "Kaitlin", "Kaley",
    "Karen", "Kate", "Katharine", "Katherine", "Kathryn", "Kathy", "Katie", "Kayvan", "Keanu", "Keegan-Michael", "Keira",
    "Keke", "Kelsey", "Ken", "Kerry", "Kevin", "Kiefer", "Kieran", "Kingsley", "Kirsten", "Kristen", "Kumail", "Kurt",
    "Kyle", "LaKeith", "Laura", "Lauren", "Laurence", "Lena", "Leonardo", "Leslie", "Letitia", "Liam", "Liev", "Lily",
    "Linda", "Lindsay", "Lisa", "Logan", "Ludwig", "Lupita", "Macaulay", "Mackenyu", "Mads", "Maggie", "Mahershala",
    "Maika", "Maisie", "Malcolm", "Marc", "Margot", "Maria", "Marion", "Marisa", "Mark", "Marlon", "Martin", "Mary",
    "Matt", "Matthew", "Maura", "Maya", "Mel", "Melanie", "Melissa", "Meryl", "Michael", "Michelle", "Mickey", "Mila",
    "Miles", "Millie", "Milo", "Mindy", "Minnie", "Morfydd", "Morgan", "Moses", "Naomie", "Natalie", "Natasha", "Nathan",
    "Neil", "Nicholas", "Nick", "Nicolas", "Nicole", "Nikolaj", "Noomi", "Norman", "Octavia", "Odeya", "Olga", "Olivia",
    "Orlando", "Oscar", "Owen", "Paddy", "Patrice", "Patricia", "Patrick", "Patton", "Paul", "Pedro", "Penelope", "Peter",
    "Philip", "Phylicia", "Pierce", "Pom", "Queen", "Quinta", "Quintessa", "Rachel", "Rafe", "Raffey", "Rainn", "Ralph",
    "Rami", "Randall", "Rashida", "Ray", "Rebecca", "Rebel", "Reese", "Regina", "Renee", "Rhona", "Rhys", "Richard",
    "Rinko", "Rita", "Riz", "Rob", "Robert", "Robin", "Ron", "Rosamund", "Rosario", "Rose", "Rosie", "Rupert", "Russell",
    "Ryan", "Sacha", "Sadie", "Salma", "Sam", "Samara", "Samuel", "Sanaa", "Sandra", "Saoirse", "Sarah", "Scarlett",
    "Scott", "Sean", "Sebastian", "Selena", "Seth", "Shah", "Shailene", "Sharon", "Shaun", "Shea", "Shia", "Shirley",
    "Sidney", "Sigourney", "Simone", "Simu", "Sissy", "Skeet", "Sofia", "Sonequa", "Sophia", "Spike", "Stanley",
    "Stellan", "Stephanie", "Steve", "Steven", "Suraaj", "Susan", "Sydney", "Sylvester", "Taika", "Tao", "Taraji",
    "Taran", "Taron", "Tatiana", "Tessa", "Teyonah", "Thandiwe", "Thomasin", "Thuso", "Tilda", "Tim", "Timothee", "Tina",
    "Tobey", "Toby", "Tom", "Tommy", "Toni", "Tony", "Topher", "Trevante", "Tuppence", "Uma", "Uzo", "Valerie",
    "Vanessa", "Vera", "Vicky", "Viggo", "Vin", "Vince", "Viola", "Walton", "Warwick", "Wesley", "Whoopi", "Will",
    "Willem", "William", "Woody", "Wunmi", "Yahya", "Yvonne", "Zac", "Zach", "Zachary", "Zazie", "Zoe"
};

static const char* popular_actor_lastnames[] = {
    "Abdi", "Abdul-Mateen II", "Ackles", "Adams", "Aduba", "Affleck", "Ahmed", "Alexander", "Ali", "Allen", "Anderson",
    "Aniston", "Applegate", "Aranas", "Arquette", "Atwell", "Aykroyd", "Bacall", "Baldwin", "Bale", "Banderas", "Bang",
    "Banks", "Bardem", "Baron Cohen", "Barrymore", "Bassett", "Bates", "Bautista", "Bean", "Beetz", "Bell", "Bello",
    "Ben-Adir", "Bening", "Bergman", "Berry", "Bichir", "Biles", "Binoche", "Birch", "B. Jordan", "Blanchett", "Bloom",
    "Blunt", "Bobby Brown", "Bogart", "Bonham Carter", "Borgnine", "Boutella", "Brando", "Bridges", "Brie", "Britton",
    "Brody", "Brolin", "Brooks", "Brosnan", "Brown", "Brunson", "Bullock", "Buscemi", "Busey", "Butler", "Byrne", "Cage",
    "Cardellini", "Carrey", "Cassidy", "Cavill", "Cena", "Chalamet", "Chan", "Chase", "Chastain", "Chau", "Cheadle",
    "Christensen", "Christie", "Clark", "Clooney", "Close", "Collette", "Colman", "Connery", "Considine", "Cooper",
    "Coster-Waldau", "Costner", "Cotillard", "Courtney", "Cox", "Cranston", "Crawford", "Crowe", "Crudup", "Cruz",
    "Culkin", "Cumberbatch", "Cuoco", "Daddario", "Dafoe", "Damon", "Dance", "Davis", "Dawson", "Day", "de Armas",
    "DeGeneres", "DeHaan", "Del Toro", "De Niro", "Depp", "Dern", "DeVito", "Diaz", "DiCaprio", "Dickinson", "Diesel",
    "Dinklage", "Driver", "Dunst", "Eastwood", "Edebiri", "Edgerton", "Efron", "Egerton", "Ehrenreich", "Eisenberg",
    "Ejiofor", "Elba", "Elordi", "Esposito", "Estevez", "Evans", "Falco", "Fanning", "Faris", "Farmiga", "Farrell",
    "Ferguson", "Fey", "Fiennes", "Fillion", "Firth", "Fishback", "Fishburne", "Fisher", "Flynn", "Fonda", "Ford",
    "Foster", "Freeman", "Gable", "Gadot", "Galifianakis", "Garcia Bernal", "Garfield", "Garland", "Gere", "Giamatti",
    "Gibson", "Gillan", "Gilliam", "Gleeson", "Goggins", "Goldberg", "Goldblum", "Goldwyn", "Gomez", "Gonzalez",
    "Gooding Jr.", "Goodwin", "Gordon-Levitt", "Gosling", "Grace", "Grace Moretz", "Grammer", "Grant", "Griffith",
    "Grillo", "Grint", "Gruffudd", "Gurira", "Gyllenhaal", "Hackman", "Hahn", "Hamm", "Hammer", "Hanks", "Harbour",
    "Harlow", "Harper", "Harrelson", "Harris", "Hathaway", "Hauser", "Hawke", "Hawkins", "Hawn", "Hayek", "Headey",
    "Heard", "Hedlund", "Heigl", "Hepburn", "Highmore", "Hill", "Hinds", "Hirsch", "H. Macy", "Hodge", "Hoffman",
    "Holbrook", "Holland", "Holmes", "Hopkins", "Hopper", "Hoult", "Hounsou", "Hudson", "Hunter", "Huston", "Ifans",
    "Ingram", "Ironside", "Isaac", "Jackman", "James", "Janney", "Janssen", "Jeong", "Jessica Parker", "Johansson",
    "Johnson", "Jolie", "Jones", "Kaling", "Kamal", "Kazan", "Keach", "Keaton", "Keitel", "Keoghan", "Key", "Kidman",
    "Kier", "Kikuchi", "Killam", "King", "Kirby", "Klementieff", "Knightley", "Kravitz", "Krieps", "Kudrow", "Kunis",
    "Kurylenko", "Kuss", "LaBeouf", "Larson", "Lathan", "Latifah", "Law", "Leachman", "Ledger", "Lee", "Lee Jones",
    "Lehman", "Leigh", "Lerman", "Levin", "Levy", "Lewis", "Li", "Liotta", "Liu", "L. Jackson", "Lopez", "Loren",
    "Louis-Dreyfus", "Lowe", "Lyonne", "Macdonald", "MacLachlan", "Madekwe", "Maguire", "Malek", "Malone", "Manning",
    "Margret", "Maron", "Martindale", "Martin-Green", "Maslany", "Mbatha-Raw", "Mbedu", "McAdams", "McCarthy",
    "McClanahan", "McDormand", "McDowell", "McElhone", "McGregor", "McKellen", "McKenzie", "McNairy", "Melchior",
    "Mendes", "Meyer", "Middleton", "Mikkelsen", "Minifie", "Mirren", "Mitra", "Molina", "Monroe", "Moore", "Moreno",
    "Mortensen", "Mosaku", "Moss", "Mount", "Mulligan", "Mulroney", "Muniz", "Murphy", "Nanjiani", "Neeson", "Newton",
    "Nolte", "Norton", "Novak", "Nyong'o", "Odenkirk", "Odom Jr.", "O'Donnell", "Oh", "Okamoto", "Oldman", "Olsen",
    "O'Neill", "Orser", "Ortega", "Oswalt", "Pacino", "Page", "Palmer", "Paltrow", "Park", "Parris", "Pascal", "Patel",
    "Patrick Harris", "Pattinson", "Peele", "Perlman", "Perry", "Pesci", "Peters", "P. Henson", "Phoenix", "Pike",
    "Plaza", "Poesy", "Poitier", "Poots", "Portman", "Posey", "Powell", "Pryce", "Pugh", "Purohit", "Quaid", "Quinn",
    "Quinto", "Radcliffe", "Rae", "Rapace", "Rashad", "Redmayne", "Reedus", "Reeves", "Reitman", "Renner", "Reynolds",
    "Rhames", "Rhodes", "Richards", "Richardson", "Rickman", "Riseborough", "Robbie", "Roberts", "Rockwell", "Rodriguez",
    "Rogen", "Rogowski", "Ronan", "Rourke", "Rudolph", "Ruffalo", "Rukh Khan", "Rush", "Russell", "Saldana", "Sanada",
    "Sandler", "Sarandon", "Schreiber", "Schwarzenegger", "Seinfeld", "Serkis", "Sessa", "Seyfried", "Seymour Hoffman",
    "Sharma", "Shaw", "Shawkat", "Short", "Simmons", "Sink", "Skarsgard", "Smith", "Smollett", "Smulders", "Snipes",
    "Spacek", "Spall", "Spencer", "Stallone", "Stan", "Stanfield", "Starr", "Statham", "Staunton", "Steenburgen",
    "Steinfeld", "Stenberg", "Stevens", "Stewart", "Stone", "Strahovski", "Streep", "Styles", "Sutherland", "Swank",
    "Swayze", "Sweeney", "Swindell", "Swinton", "Tatum", "Taylor", "Taylor-Johnson", "Taylor-Joy", "Teller", "Temple",
    "Theron", "Thompson", "Thurman", "Thwaites", "Tierney", "Timberlake", "Tomei", "Tucci", "Tyson", "Ulrich", "Uwais",
    "Van Dien", "Vaughn", "Ventimiglia", "Vikander", "Wahlberg", "Waititi", "Walken", "Walker", "Waller-Bridge", "Waltz",
    "Washington", "Weathers", "Weaver", "Weaving", "Whigham", "Whitaker", "Whitehead", "Wiig", "Williams", "Willis",
    "Wilson", "Winston", "Witherspoon", "Wolfhard", "Wong", "Wood", "Wright", "Yelchin", "Yeoh", "Yeun", "Zellweger",
    "Zeta-Jones"
};

// A macro to get the number of elements in the arrays.
#define ACTORS_FNAME_COUNT (sizeof(popular_actor_firstnames) / sizeof(popular_actor_firstnames[0]))
#define ACTORS_LNAME_COUNT (sizeof(popular_actor_lastnames) / sizeof(popular_actor_lastnames[0]))

#endif // POPULAR_ACTORS_H
