
<?php
/*
 * DVD Store Get Row Count PHP Page - dsgetrowcount.php
 *
 * Copyright (C) 2025 Red Hat, Inc.
 *
 * Returns row count for a specified table
 *
 * Generated by Claude Code (Anthropic)
 *
 * Last Updated 7/30/26
 *
 * Support for PHP 8 and Oracle OCI8
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

include("dscommon.inc");

ds_html_header("Get Row Count");

$tablename = $_REQUEST["tablename"];
$storenum = isset($_REQUEST["storenum"]) ? $_REQUEST["storenum"] : 1;

if (empty($tablename))
  {
  echo "<H2>Error: No table name specified</H2>\n";
  ds_html_footer();
  exit;
  }

$conn = oci_pconnect($oracle_user, $oracle_password, $oracle_connstr);
if (!$conn) {
  $e = oci_error();
  die("Oracle connection failed: " . htmlentities($e['message'], ENT_QUOTES));
}

// Execute COUNT(*) query - Oracle table names are case-sensitive in schema DS3
$sql = "SELECT COUNT(*) FROM DS3.$tablename";
$stmt = oci_parse($conn, $sql);

if (!oci_execute($stmt))
  {
  $e = oci_error($stmt);
  echo "<H2>Error executing query: " . htmlentities($e['message'], ENT_QUOTES) . "</H2>\n";
  oci_free_statement($stmt);
  oci_close($conn);
  ds_html_footer();
  exit;
  }

$row = oci_fetch_array($stmt, OCI_NUM);
$rowcount = $row[0];
oci_free_statement($stmt);
oci_close($conn);

// Return rowcount in hidden input field (matches expected parse format from web driver)
echo "<INPUT TYPE=HIDDEN NAME=rowcount VALUE=$rowcount>\n";

ds_html_footer();
?>
